source "https://rubygems.org"

# Specify your gem's dependencies in diaper_bag.gemspec


gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem 'nokogiri', '~> 1.11', '>= 1.11.1'
gem 'httparty', '~> 0.18.1'
gem 'pry'